### ISSUE TITLE
change text at top-right in song wheel to display current mode (single/versus/routine)

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/Simply-Love-SM5#13]
seems more useful imo

![image](https://user-images.githubusercontent.com/1487413/53285683-09da5080-3729-11e9-8dfd-eac3d35a6776.png)

**Comment by andrewipark** [comment]
I personally like the metrics text because I want to know what I'm playing if I'm hopping on, but it can probably be stuffed somewhere else.

You can technically distinguish single/double and versus by the player join indicators but this is *really* opaque.
