### ISSUE TITLE
toss use a usb card, song high score scrolls for ScreenAttract

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/Simply-Love-SM5#14]

**Comment by andrewipark** [comment]
I wonder if this removal would also get rid of the insane amount of lag when this screen switches out.

**Comment by andrewipark** [comment]
current status: patch made, undergoing testing.

**Comment by andrewipark** [comment]
ScreenRanking was removed, but I've kept "use a usb card" because it actually works in SM5.1 beta.
