### ISSUE TITLE
ScreenSummary center header is sized weirdly

### ISSUE THREAD

**Issue by andrewipark** [ddrillini/Simply-Love-SM5#17]
I fixed this a *long* time ago in stock, so I don't know why this one is still weird.

Header size in general should probably just be a "metric" since it affects global display state.

**Comment by dguzek** [comment]
It's unclear what you're describing here; it may have been fixed in https://github.com/dguzek/Simply-Love-SM5/commit/eff85f70ca933f23439c00fbfeec5b4da96be8f1.

**Comment by andrewipark** [comment]
It wasn't that.

**Comment by andrewipark** [comment]
Looks like it was fixed in upstream, although maybe not from that particular commit.

**Comment by quietly-turning** [comment]
![mystery](https://user-images.githubusercontent.com/1253483/76118893-3f607d80-5fbc-11ea-909d-807b58608525.jpg)
