### ISSUE TITLE
it's time for SL to die. what's next?

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/Simply-Love-SM5#23]
Dan doesn't want to be associated with the theme anymore. 

We don't want it to be called SL anymore, because we don't wanna tie it back to him.

I propose we do a visual overhaul such that it's effectively a different theme. In this way, it "dies" and is reborn as something else.

![image](https://user-images.githubusercontent.com/1487413/53486281-ecb9c080-3a4d-11e9-8f2a-95d8e0e08eef.png)

---

Tracking some ideas in #24.

**Comment by andrewipark** [comment]
same issues as present in #11

**Comment by Sereni** [comment]
I'm sorry to bring this up, but have you considered
1. that this is the continuation of the original SL not started by Dan (credits to Lara et al?) and
2. how will we as a community deal with developing this further, even if Dan does not want to be involved?

I don't mind the name change per se, but it doesn't make people forget that this looks awfully like SL. I'm worried about is how fragmented new features might become when developed under new names and branches. Many people develop features for SL, some of the best things came from others, and I believe it will be a loss for the community if we let it fall apart.

I know there needs to be a longer term solution, and this is not it, but thought I'd share with you folks.  

Dan did ask my opinion about this before deleting his accounts, I would love to discuss it with him, but I'm unable unfortunately.

**Comment by ianklatzco** [comment]
1. `that this is the continuation of the original SL not started by Dan (credits to Lara et al?)` I hadn't thought that far. We'd probably leave an acknowledgements section with Matt and Lara, but I suspect Dan would want to be removed.
2. `how will we as a community deal with developing this further` Perhaps with something that no longer looks like Simply Love.
