### ISSUE TITLE
UI Gripes

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/Simply-Love-SM5#24]
intended to be a running thread for overhaul purposes
* Lack of BPM display on ScreenEval
* Lack of separate field for stamina breakdowns
* lack of song duration

**Comment by andrewipark** [comment]
The second one already exists. If you use `ssc` files, the theme will read the `#CREDIT`, `#DESCRIPTION`, and `#CHARTNAME` tags of the individual chart in question, and cycle through displaying them.

Granted, very few people are willing to use `ssc`, but come on, it's 2019.

**Comment by ianklatzco** [comment]
difficulty blocks should be removed as they are a waste of space

**Comment by ianklatzco** [comment]
make stepartist text dark if rainbow mode is on

![image](https://user-images.githubusercontent.com/1487413/55676073-c11ec700-5892-11e9-8110-43465722c1dc.png)

**Comment by ianklatzco** [comment]
* stepartist on song when the playfield loads first time
