### ISSUE TITLE
If you're in ECFA mode, "disable decents and wayoffs" actually disables greats and decents.

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/Simply-Love-SM5#26]
![image](https://user-images.githubusercontent.com/1487413/53640122-e748ab80-3bf0-11e9-8806-3468af3e7258.png)

Looks like it's here:
https://github.com/ddrillini/Simply-Love-SM5/blob/aaee3d038867862fcd751d6f4db9166f286829a1/Scripts/SL-PlayerOptions.lua#L292

---

Andrew:

With 3d62425 it is now possible to get the OptionsRow to dynamically change the displayed option strongs, but still have them map to the same choices engine side. Unfortunately, this does not apply to the (promptly localized) name of the OptionRow.

I wonder if binding (yet another, ugh) property in the table for a given OptionRow will work:
```lua
-- in a given OptionRow
name = function() return "do stuff here" end
-- insert this into OptionRowDefault to replace line ~452
if Overrides[name].NameFunction then
    self.name = Overrides[name].NameFunction()
else self.name = name end
```

**Comment by andrewipark** [comment]
I need to overhaul some of the way this is laid out anyways... it was fine until I added my thing and now the if-else structure is driving me insane.

**Comment by dguzek** [comment]
Fixed in https://github.com/dguzek/Simply-Love-SM5/commit/b41cfdd366bd5e49eea33743723c9a8f631ee241.

**Comment by andrewipark** [comment]
:heavy_check_mark:

**Comment by dguzek** [comment]
Thank you for closing this.
