### ISSUE TITLE
RIP quick fixes

### ISSUE THREAD

**Issue by andrewipark** [ddrillini/Simply-Love-SM5#29]
I got bodied this year, but I should be able to do all of this reasonably quickly

* Add EX score delta to the middle of the screen to aid commentators
* fix score weights to 5-4-3-0
* D/WO off

**Comment by ianklatzco** [comment]
EX delta thing on ScreenEval only?

**Comment by andrewipark** [comment]
No, this would be during gameplay. I observed commentary and found that a lot of time was spent trying to guess at exact score difference. On ScreenEval, if the EX score difference is small enough to matter you can usually just glance at the EX counts anyways.

**Comment by ianklatzco** [comment]
this would probably be distracting to players.
