### ISSUE TITLE
make difficulty / stepartist text dark if rainbow mode is on

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/Simply-Love-SM5#36]
![image](https://user-images.githubusercontent.com/1487413/54807912-ade1e980-4c4c-11e9-9b62-7925ae17bab2.png)

**Comment by ianklatzco** [comment]
moved to #24

**Comment by dguzek** [comment]
Fixed in https://github.com/dguzek/Simply-Love-SM5/commit/ec5e2aa81411738a20339fefb4620648bb22a8a1.
