### ISSUE TITLE
multiple judgment fonts starting w/ same characters

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/Simply-Love-SM5#39]
I'm still having this locally. I didn't see it on our issue tracker.

Upon starting a song:

ThemeManager:  There is more than one theme element that matches 'Simply-Love-SM5/Graphics/_judgments/Competitive/Love'. 

Please remove all but one of these matches:
* /Themes/Simply-Love-SM5/Graphics/_judgments/Competitive/Love_Chroma 2x6 (doubleres).png
* /Themes/Simply-Love-SM5/Graphics/_judgments/Competitive/Love_Chroma 2x6 (doubleres).png
* /Themes/Simply-Love-SM5/Graphics/_judgments/Competitive/Love_Redux 2x6 (doubleres).png

![image](https://user-images.githubusercontent.com/1487413/55676046-3938bd00-5892-11e9-89e6-5a4f3fb33101.png)

**Comment by ianklatzco** [comment]
@andrewipark, what was the exact problem?

It looks like it's because the files are named `Love_*`. My guess would be that Stepmania parses them in a weird way, treating the underscore and the spaces as the same thing.

**Comment by dguzek** [comment]
Fixed in https://github.com/dguzek/Simply-Love-SM5/commit/288aec70ab3182e9d11b4c5dc069cc05af525ead.
