### ISSUE TITLE
String match on some judgement fonts?

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/Simply-Love-SM5#5]
<img width="1280" alt="screenshot 2018-08-13 15 06 04" src="https://user-images.githubusercontent.com/1487413/44061197-43226554-9f0c-11e8-931f-284c1a780ac9.png">
<img width="504" alt="screenshot 2018-08-13 15 18 03" src="https://user-images.githubusercontent.com/1487413/44061198-4341bd82-9f0c-11e8-81d9-c5716b5f3249.png">

**Comment by sangyeolbaek** [comment]
I also had that same problem

I am not exactly sure how to silence that warning, but my guess is that you have folders outside the theme directory that contain the same files

**Comment by ianklatzco** [comment]
I believe it's related to something Andrew did. He'll take a look at some point soon.

**Comment by andrewipark** [comment]
It's a Stepmania quirk with loading graphics names, so this also exists in stock Simply Love. I've prepared a patch but it needs a few days for testing.

**Comment by andrewipark** [comment]
Closing in favor of upstream discussion (if applicable)

**Comment by ianklatzco** [comment]
instructing kysee, alexa, and emilia to git pull in their simply love dirs

**Comment by ianklatzco** [comment]
wait that only works once we merge upsteram into ours

**Comment by andrewipark** [comment]
this won't be until later tomorrow, because apparently another PR is getting merged into master today
