### ISSUE TITLE
move more things into theme-side OptionRows

### ISSUE THREAD

**Issue by andrewipark** [ddrillini/Simply-Love-SM5#8]
More of a personal thing as I move towards my own theme, for config's sake.

This should also help as I start moving more and more things into the theme that ... not everyone will want on by default.

Current qualms with the number of option rows are unfortunately blocked by the lack of other viable input methods (e.g. touchscreen, mouse).

**Comment by ianklatzco** [comment]
Can you elaborate? What sorts of things are you moving into the theme-side? Where are you moving them from?

**Comment by andrewipark** [comment]
announcer voices, cue for low life, etc. (its not really clear yet but nothing super major)

**Comment by ianklatzco** [comment]
Where are you moving them from? Where are you moving them to?

Is this options menu right before a song vs. the operator menu?

**Comment by andrewipark** [comment]
new toggles for previously untoggleable behavior

**Comment by ianklatzco** [comment]
i see. shouldn't this be upstream?

**Comment by andrewipark** [comment]
> i see. shouldn't this be upstream?

> Current qualms with the number of option rows

Multiple PRs with toggle-ables have been blocked. This is for valid reasons, but I have slightly different opinions on what level of options exposure is acceptable.

**Comment by andrewipark** [comment]
This issue is too broad.
